language: ruby
sudo: false
cache: bundler

rvm:
  - 2.3.3

env:
  - DB=mysql
  - DB=pg

matrix:
  allow_failures:
    - env: DB=pg

before_install:
  - 'cp "config.yml.${DB}.travis" "config.yml"'

before_script:
  - 'if [ "$DB" = "pg" ]; then psql -c "create database myapp;" -U postgres; fi'
  - bundle exec rake dummy:setup

script: xvfb-run bundle exec rake ci
