# Serving
baseurl: "/releaf"


defaults:
  -
    scope:
      path: ""
    values:
      site-title: "Releaf"
  -
    scope:
      path: "documentation"
    values:
      layout: documentation
      group: documentation
